--- 
title: "Data Management How-To's"
author: "Vicky Steeves and Nick Wolf"
date: "`r Sys.Date()`"
description: "Open educational resources for learning data management best practices"
site: bookdown::bookdown_site
colorlinks: yes
documentclass: book
always_allow_html: yes
output:
  bookdown::gitbook:
    css: [style.css]
    config:
      toc:
        before: |
          <p>Data Management How-To's</p>
          <p>NYU Data Services</p>
        after: |
          <p><a href="https://gitlab.com/RLesur/bookdown-gitlab-pages" target="blank">Published with bookdown &amp; GitLab</a></p>
          <p>Original content is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.</p>
          <p>Any questions, contact: <a href="mailto:vicky.steeves@nyu.edu">vicky.steeves@nyu.edu</a></p>
      edit: https://gitlab.com/nyu-dataservices/rdm-instruction/edit/master/%s
      search: yes
      download: ["pdf", "epub"]
      sharing: null
  bookdown::pdf_book:
    latex_engine: xelatex
  bookdown::epub_book: default
---

# Welcome {-}

Give some introduction to this book.

# Task list {-}

Checklist for Nick:

- [ ] write the welcome paragraph on this page
- [ ] [put a pic and a short bio on the authors page](introduction.html#about-the-authors)
- [ ] [how to read this book](introduction.html#how-to-read-this-book)
- [ ] [directory structure + zotero for file mgmt](data-management-first-steps.html#directory-structure)
- [ ] [documentation](data-management-first-steps.html#file-naming)
- [ ] [data processing chapter](data-processing.html)
- [ ] [grant chapter](grant-applications.html)

Checklist for Vicky: 

* [ ] [how to do the exercises](introduction.html#how-to-do-the-exercises)
* [ ] [put a pic and a short bio on the authors page](introduction.html#about-the-authors)
* [ ] [principles of rdm](data-management-first-steps.html#principles-of-efficient-data-management)
* [ ] [file naming](data-management-first-steps.html#file-naming)
* [ ] [file format selection](data-management-first-steps.html#file-format-selection)
* [ ] [storage and backup](data-management-first-steps.html#storage-backup)
* [ ] [version control for not code](data-management-first-steps.html#version-control-for-not-code)
* [ ] [project management and collab chapter](project-management-collaboration.html)

